### ISSUE TITLE
Hast du mal mit FEN Notation gearbeitet??

### ISSUE THREAD

**Issue by rokemHB** [Smarcy/nim_chess#1]

**Comment by Smarcy** [comment]
Gearbeitet nicht, aber Wikipedia hat da afaik ne ziemlich gute Aufdröselung. Und Lichess kann dir auf jeden Fall auch FEN rausschmeißen!

**Comment by rokemHB** [comment]
überlege das halt auf die 4 player situation zu erweitern, aber aktuell mache ich es doch erstmal sehr object heavy.. Da wird undo / history aber schwer, mit FEN könnte man das relativ easy implementieren

**Comment by rokemHB** [comment]
Haha schön meinen shit gestohlen <3

**Comment by Smarcy** [comment]
Mit Credits! :D <3
